version: "3.9"

networks:
  arr_net:
    driver: bridge

services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Lisbon
    networks: [arr_net]
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Lisbon
    volumes:
      - /volume1/docker/arr/prowlarr:/config
    networks: [arr_net]
    ports:
      - "9696:9696"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
    depends_on: [flaresolverr]
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Lisbon
    volumes:
      - /volume1/docker/arr/sonarr:/config
      - /volume1/downloads:/downloads
      - /volume1/media/tv:/tv
    networks: [arr_net]
    ports:
      - "8989:8989"
    depends_on: [prowlarr]
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Lisbon
    volumes:
      - /volume1/docker/arr/radarr:/config
      - /volume1/downloads:/downloads
      - /volume1/media/movies:/movies
    networks: [arr_net]
    ports:
      - "7878:7878"
    depends_on: [prowlarr]
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Lisbon
    volumes:
      - /volume1/docker/arr/bazarr:/config
      - /volume1/downloads:/downloads
      - /volume1/media/tv:/tv
      - /volume1/media/movies:/movies
    networks: [arr_net]
    ports:
      - "6767:6767"
    depends_on: [sonarr, radarr]
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Lisbon
      - WEBUI_PORT=8080
    volumes:
      - /volume1/docker/arr/qbittorrent:/config
      - /volume1/downloads:/downloads
    ports:
      - "8080:8080"        # WebUI
      - "6881:6881"        # TCP peers
      - "6881:6881/udp"    # UDP peers
    networks: [arr_net]
    restart: unless-stopped

  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    environment:
      - TZ=Europe/Lisbon
    networks: [arr_net]
    ports:
      - "1880:80"     # Proxy Hosts (LAN)
      - "81:81"       # Dashboard (LAN)
      - "18443:443"   # HTTPS interno (opcional)
    volumes:
      - /volume1/docker/arr/npm/data:/data
      - /volume1/docker/arr/npm/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
